// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: pkg/snapshot/api/snapshot.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SnapshotAPIClient is the client API for SnapshotAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotAPIClient interface {
	RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type snapshotAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotAPIClient(cc grpc.ClientConnInterface) SnapshotAPIClient {
	return &snapshotAPIClient{cc}
}

func (c *snapshotAPIClient) RequestSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/snapshot.v1.SnapshotAPI/RequestSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotAPIServer is the server API for SnapshotAPI service.
// All implementations must embed UnimplementedSnapshotAPIServer
// for forward compatibility
type SnapshotAPIServer interface {
	RequestSnapshot(context.Context, *SnapshotRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSnapshotAPIServer()
}

// UnimplementedSnapshotAPIServer must be embedded to have forward compatible implementations.
type UnimplementedSnapshotAPIServer struct {
}

func (UnimplementedSnapshotAPIServer) RequestSnapshot(context.Context, *SnapshotRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSnapshot not implemented")
}
func (UnimplementedSnapshotAPIServer) mustEmbedUnimplementedSnapshotAPIServer() {}

// UnsafeSnapshotAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotAPIServer will
// result in compilation errors.
type UnsafeSnapshotAPIServer interface {
	mustEmbedUnimplementedSnapshotAPIServer()
}

func RegisterSnapshotAPIServer(s grpc.ServiceRegistrar, srv SnapshotAPIServer) {
	s.RegisterService(&SnapshotAPI_ServiceDesc, srv)
}

func _SnapshotAPI_RequestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAPIServer).RequestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapshot.v1.SnapshotAPI/RequestSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAPIServer).RequestSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotAPI_ServiceDesc is the grpc.ServiceDesc for SnapshotAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshot.v1.SnapshotAPI",
	HandlerType: (*SnapshotAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestSnapshot",
			Handler:    _SnapshotAPI_RequestSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/snapshot/api/snapshot.proto",
}
