// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"path"
	"regexp"
	"strings"
)

// Deterministic gates for the pgstream PR approval agent.
//
// Gates are authoritative: they run before the LLM and the LLM can only tighten
// their verdict, never loosen it. A path that lands in the deny-list is escalated
// to a human regardless of what the model thinks of the code.
//
// This mirrors PostHog's stamphog design, retuned for pgstream's Go + SQL layout:
// no ownership model, no Django migration heuristics, no analytics — just path
// classification, a size ceiling, and a small deny-list.

// Escalate (never auto-approve) anything larger than these ceilings. A change
// this big cannot be reviewed with confidence from a diff by an agent.
const (
	maxSubstantiveLines = 800
	maxSubstantiveFiles = 30
)

type pathRule struct {
	pattern  *regexp.Regexp
	category string
}

// denyPaths must always go to a human. Ordered; first match wins per file.
var denyPaths = []pathRule{
	{regexp.MustCompile(`^migrations/`), "migration"},
	{regexp.MustCompile(`^\.github/workflows/`), "ci-cd"},
	{regexp.MustCompile(`^\.github/`), "ci-cd"},
	{regexp.MustCompile(`^\.goreleaser.*\.ya?ml$`), "release/supply-chain"},
	{regexp.MustCompile(`(^|/)Dockerfile$`), "release/supply-chain"},
	{regexp.MustCompile(`^go\.(mod|sum)$`), "dependencies"},
	// The agent must never be able to approve edits to its own logic or policy.
	{regexp.MustCompile(`^tools/pr-approval-agent/`), "review-agent-self"},
	{regexp.MustCompile(`^(LICENSE|license-header\.txt)$`), "legal"},
}

// scrutinyPaths are legitimate but correctness-critical: not denied, but
// surfaced to the LLM so it applies extra scrutiny and leans toward ESCALATE.
var scrutinyPaths = []pathRule{
	{regexp.MustCompile(`^pkg/wal/replication/`), "replication-core"},
	{regexp.MustCompile(`^pkg/wal/checkpointer/`), "checkpoint-core"},
	{regexp.MustCompile(`^pkg/wal/listener/`), "wal-listener"},
	{regexp.MustCompile(`^pkg/snapshot/`), "snapshot-core"},
	{regexp.MustCompile(`^pkg/wal/processor/postgres/`), "postgres-writer"},
}

// trivialPaths carry little behavioural risk: excluded from the size ceiling,
// and a PR touching only these can be auto-approved without an LLM call.
var trivialPaths = []*regexp.Regexp{
	regexp.MustCompile(`\.md$`),
	regexp.MustCompile(`^docs/`),
	regexp.MustCompile(`_test\.go$`),
	regexp.MustCompile(`(^|/)testdata/`),
	regexp.MustCompile(`(^|/)mocks?/`),
	regexp.MustCompile(`_mocks?\.go$`),
	regexp.MustCompile(`^coverage/`),
	// Generated definition artifacts, regenerated by `make generate`.
	regexp.MustCompile(`^(cli-definition|transformers-definition)\.json$`),
}

type changedFile struct {
	Path      string `json:"path"`
	Additions int    `json:"additions"`
	Deletions int    `json:"deletions"`
}

type classification struct {
	Tier             string   `json:"tier"` // "T0-trivial" | "T1-agent" | "T2-never"
	DenyCategories   []string `json:"deny_categories"`
	ScrutinyFlags    []string `json:"scrutiny_flags"`
	SubstantiveLines int      `json:"substantive_lines"`
	SubstantiveFiles int      `json:"substantive_files"`
	TrivialOnly      bool     `json:"trivial_only"`
}

type gateResult struct {
	Allow   bool     `json:"allow"`   // may the LLM even be consulted?
	Verdict string   `json:"verdict"` // "PASS" | "ESCALATE"
	Reasons []string `json:"reasons"`
}

func normPath(p string) string {
	p = strings.TrimSpace(p)
	p = strings.TrimPrefix(p, "./")
	return path.Clean(p)
}

func isTrivial(p string) bool {
	for _, re := range trivialPaths {
		if re.MatchString(p) {
			return true
		}
	}
	return false
}

func appendUnique(list []string, v string) []string {
	for _, existing := range list {
		if existing == v {
			return list
		}
	}
	return append(list, v)
}

// classify deterministically categorises a set of changed files.
//
// Ordering matters: deny wins over everything (a single dangerous file taints the
// whole PR), then trivial-only, then default agent review.
func classify(files []changedFile) classification {
	c := classification{
		DenyCategories: []string{},
		ScrutinyFlags:  []string{},
		TrivialOnly:    true,
	}

	for _, f := range files {
		p := normPath(f.Path)

		for _, rule := range denyPaths {
			if rule.pattern.MatchString(p) {
				c.DenyCategories = appendUnique(c.DenyCategories, rule.category)
			}
		}
		for _, rule := range scrutinyPaths {
			if rule.pattern.MatchString(p) {
				c.ScrutinyFlags = appendUnique(c.ScrutinyFlags, rule.category)
			}
		}

		if isTrivial(p) {
			continue
		}
		c.TrivialOnly = false
		c.SubstantiveFiles++
		c.SubstantiveLines += f.Additions + f.Deletions
	}

	switch {
	case len(c.DenyCategories) > 0:
		c.Tier = "T2-never"
		c.TrivialOnly = false
	case c.TrivialOnly:
		c.Tier = "T0-trivial"
	default:
		c.Tier = "T1-agent"
	}

	return c
}

// runGates applies the authoritative gates to a classification. Allow=false means
// the PR must not be auto-approved. Allow=true means the LLM may be consulted (or,
// for T0-trivial, auto-approval is permitted).
func runGates(c classification, mergeable string) gateResult {
	if mergeable == "CONFLICTING" {
		return gateResult{
			Allow:   false,
			Verdict: "ESCALATE",
			Reasons: []string{"PR has merge conflicts; rebase before review"},
		}
	}
	if len(c.DenyCategories) > 0 {
		return gateResult{
			Allow:   false,
			Verdict: "ESCALATE",
			Reasons: []string{"touches deny-listed area(s) requiring human review: " + strings.Join(c.DenyCategories, ", ")},
		}
	}
	if c.SubstantiveLines > maxSubstantiveLines {
		return gateResult{
			Allow:   false,
			Verdict: "ESCALATE",
			Reasons: []string{fmt.Sprintf("%d substantive lines exceeds the %d-line ceiling for auto-review", c.SubstantiveLines, maxSubstantiveLines)},
		}
	}
	if c.SubstantiveFiles > maxSubstantiveFiles {
		return gateResult{
			Allow:   false,
			Verdict: "ESCALATE",
			Reasons: []string{fmt.Sprintf("%d substantive files exceeds the %d-file ceiling for auto-review", c.SubstantiveFiles, maxSubstantiveFiles)},
		}
	}

	reasons := []string{}
	if len(c.ScrutinyFlags) > 0 {
		reasons = append(reasons, "scrutiny areas touched: "+strings.Join(c.ScrutinyFlags, ", "))
	}
	return gateResult{Allow: true, Verdict: "PASS", Reasons: reasons}
}
