// SPDX-License-Identifier: Apache-2.0

package integration

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	pglib "github.com/xataio/pgstream/internal/postgres"
	"github.com/xataio/pgstream/internal/testcontainers"
	"github.com/xataio/pgstream/pkg/stream"
)

func Test_SnapshotToPostgres(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	// postgres container where pgstream hasn't been initialised to be used for
	// snapshot validation
	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(testTable string, opts ...option) {
		// create table and populate it before initialising and running pgstream to
		// ensure the snapshot captures pre-existing schema and data properly
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(`CREATE TABLE %s(id serial PRIMARY KEY, name TEXT, username TEXT GENERATED ALWAYS AS ('user_' || name ) STORED)`, testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf("insert into %s(name) values('a'),('b')", testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf("create role test_role_%s", testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf("grant select on %s to test_role_%s", testTable, testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		validation := func() bool {
			schemaColumns := getInformationSchemaColumns(t, ctx, targetConn, testTable)
			if len(schemaColumns) != 3 {
				return false
			}

			wantSchemaCols := []*informationSchemaColumn{
				{name: "id", dataType: "integer", isNullable: "NO"},
				{name: "name", dataType: "text", isNullable: "YES"},
				{name: "username", dataType: "text", isNullable: "YES"},
			}
			require.ElementsMatch(t, wantSchemaCols, schemaColumns)

			columns := getTestTableColumns(t, ctx, targetConn, fmt.Sprintf("select id,name,username from %s", testTable), withGeneratedColumn)
			if len(columns) != 2 {
				return false
			}

			wantCols := []*testTableColumn{
				{id: 1, name: "a", username: "user_a"},
				{id: 2, name: "b", username: "user_b"},
			}
			require.ElementsMatch(t, wantCols, columns)

			roles := getRoles(t, ctx, targetConn)
			require.NotEmpty(t, roles)
			require.Contains(t, roles, "test_role_"+testTable)

			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("snapshot2pg_bulk_integration_test", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("snapshot2pg_batch_integration_test")
	})
}

// Test_SnapshotToPostgres_IdentityOnlyTable verifies that tables where the only
// column is an identity column (e.g. id-only lookup tables) are correctly
// snapshotted, and that their values are preserved so that foreign key
// references from child tables remain valid.
func Test_SnapshotToPostgres_IdentityOnlyTable(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		parentTable := fmt.Sprintf("parent_identity_%s", suffix)
		childTable := fmt.Sprintf("child_identity_%s", suffix)

		// Create a parent table where id is the only column (identity).
		// This is the minimal repro: filterRowColumns used to filter out
		// all columns, producing zero insert queries.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`, parentTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id) VALUES (100),(200),(300)`, parentTable))

		// Create a child table that references the parent via FK.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				parent_id INTEGER NOT NULL REFERENCES %s(id),
				name TEXT
			)`, childTable, parentTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, parent_id, name) VALUES (1, 100, 'a'),(2, 200, 'b'),(3, 300, 'c')`, childTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		validation := func() bool {
			// Verify parent table: all 3 rows with exact id values preserved
			parentRows := getIDRows(t, ctx, targetConn, fmt.Sprintf("SELECT id FROM %s ORDER BY id", parentTable))
			if len(parentRows) != 3 {
				return false
			}
			require.Equal(t, []int{100, 200, 300}, parentRows)

			// Verify child table: all 3 rows with correct FK references
			childRows := getIDNameRows(t, ctx, targetConn, fmt.Sprintf("SELECT parent_id, name FROM %s ORDER BY id", childTable))
			if len(childRows) != 3 {
				return false
			}
			wantChildren := []idNameRow{
				{id: 100, name: "a"},
				{id: 200, name: "b"},
				{id: 300, name: "c"},
			}
			require.Equal(t, wantChildren, childRows)

			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync of identity-only tables")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}

// Test_SnapshotToPostgres_CubeColumns verifies that snapshot/restore
// preserves cube column values end-to-end.
//
// Regression for #801: pgx's CopyFrom serialised cube values in binary
// format and the destination COPY rejected the rows with "cube dimension
// is too large" because the leading bytes of the text representation
// were interpreted as the binary header.
func Test_SnapshotToPostgres_CubeColumns(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		testTable := fmt.Sprintf("cube_columns_%s", suffix)

		// install cube on both source and target; the test row uses a
		// 5-D cube and a 3-D box to exercise the binary-header failure
		// mode.
		for _, url := range []string{snapshotPGURL, targetPGURL} {
			execQueryWithURL(t, ctx, url, "CREATE EXTENSION IF NOT EXISTS cube")
		}

		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id  INTEGER PRIMARY KEY,
				vec cube NOT NULL
			)`, testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, vec) VALUES
				(1, cube(ARRAY[1.0, 2.0, 3.0, 4.0, 5.0])),
				(2, cube(ARRAY[0.5])),
				(3, cube('(10, 20, 30),(40, 50, 60)'))`,
			testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)
		sourceConn, err := pglib.NewConn(ctx, snapshotPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		type row struct {
			id  int
			vec string
		}
		// Pull the canonical text form from the source so the assertion
		// doesn't bake in cube output formatting quirks.
		query := fmt.Sprintf("SELECT id, vec::text FROM %s ORDER BY id", testTable)
		fetch := func(conn pglib.Querier) ([]row, error) {
			rows, err := conn.Query(ctx, query)
			if err != nil {
				return nil, err
			}
			defer rows.Close()

			out := []row{}
			for rows.Next() {
				var r row
				if err := rows.Scan(&r.id, &r.vec); err != nil {
					return nil, err
				}
				out = append(out, r)
			}
			return out, rows.Err()
		}

		want, err := fetch(sourceConn)
		require.NoError(t, err)
		require.Len(t, want, 3)

		validation := func() bool {
			got, err := fetch(targetConn)
			if err != nil || len(got) != len(want) {
				return false
			}
			require.Equal(t, want, got)
			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync of cube columns")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}

// Test_SnapshotToPostgres_LtreeColumns verifies that snapshot/restore
// preserves ltree column values end-to-end. ltree has the same root cause
// as cube (#801): pgx has no binary codec for it, so binary COPY misreads
// the leading byte of the text rep as the binary ltree version number and
// errors with "unsupported ltree version number N".
func Test_SnapshotToPostgres_LtreeColumns(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		testTable := fmt.Sprintf("ltree_columns_%s", suffix)
		for _, url := range []string{snapshotPGURL, targetPGURL} {
			execQueryWithURL(t, ctx, url, "CREATE EXTENSION IF NOT EXISTS ltree")
		}

		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id   INTEGER PRIMARY KEY,
				path ltree NOT NULL
			)`, testTable))
		// ltree labels are [A-Za-z0-9_]+ on PG14 (the test container);
		// hyphens are PG16+ so they're avoided here.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, path) VALUES
				(1, 'a.b.c'),
				(2, 'root.x1.y2.z3.leaf'),
				(3, 'Root_1.Sub_2.leaf_3_x')`,
			testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)
		sourceConn, err := pglib.NewConn(ctx, snapshotPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		type row struct {
			id   int
			path string
		}
		query := fmt.Sprintf("SELECT id, path::text FROM %s ORDER BY id", testTable)
		fetch := func(conn pglib.Querier) ([]row, error) {
			rows, err := conn.Query(ctx, query)
			if err != nil {
				return nil, err
			}
			defer rows.Close()
			out := []row{}
			for rows.Next() {
				var r row
				if err := rows.Scan(&r.id, &r.path); err != nil {
					return nil, err
				}
				out = append(out, r)
			}
			return out, rows.Err()
		}

		want, err := fetch(sourceConn)
		require.NoError(t, err)
		require.Len(t, want, 3)

		validation := func() bool {
			got, err := fetch(targetConn)
			if err != nil || len(got) != len(want) {
				return false
			}
			require.Equal(t, want, got)
			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync of ltree columns")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}

// Test_SnapshotToPostgres_MaterializedViewRefresh verifies that materialized
// views restored from a schema-only dump are refreshed after pgstream copies
// the base table data.
func Test_SnapshotToPostgres_MaterializedViewRefresh(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	suffix := time.Now().UnixNano()
	baseTable := fmt.Sprintf("mv_base_%d", suffix)
	viewName := fmt.Sprintf("mv_summary_%d", suffix)
	indexName := fmt.Sprintf("mv_summary_idx_%d", suffix)

	execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
		`CREATE TABLE %s(
			id integer PRIMARY KEY,
			name text NOT NULL
		)`, baseTable))
	execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
		`INSERT INTO %s(id, name) VALUES
			(1, 'alpha'),
			(2, 'beta')`, baseTable))
	execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
		`CREATE MATERIALIZED VIEW %s AS
			SELECT id, upper(name) AS display_name
			FROM %s
			WITH NO DATA`, viewName, baseTable))
	execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
		`CREATE UNIQUE INDEX %s ON %s(id)`, indexName, viewName))

	cfg := &stream.Config{
		Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"public.*"}),
		Processor: testPostgresProcessorCfg(),
	}
	require.NoError(t, stream.Snapshot(ctx, testLogger(), cfg, nil))

	targetConn, err := pglib.NewConn(ctx, targetPGURL)
	require.NoError(t, err)
	defer targetConn.Close(ctx)

	var count int
	err = targetConn.QueryRow(ctx, []any{&count}, fmt.Sprintf("SELECT count(*) FROM %s", viewName))
	require.NoError(t, err)
	require.Equal(t, 2, count)

	indexes := getTableIndexes(t, ctx, targetConn, "public", viewName)
	require.Contains(t, indexes, indexName)
}

// Test_SnapshotToPostgres_IdentityAndGeneratedColumns verifies that identity
// columns have their values preserved while generated (stored) columns are
// correctly excluded from inserts and recomputed by the target database.
func Test_SnapshotToPostgres_IdentityAndGeneratedColumns(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		testTable := fmt.Sprintf("identity_generated_%s", suffix)

		// Table with both an identity column (id) and a generated stored column (display_name).
		// The identity value must be preserved; the generated column must be excluded
		// from inserts and recomputed on the target.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name TEXT NOT NULL,
				display_name TEXT GENERATED ALWAYS AS ('item_' || name) STORED
			)`, testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, name) VALUES (10, 'alpha'),(20, 'beta'),(30, 'gamma')`, testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		validation := func() bool {
			rows := getTestTableColumns(t, ctx, targetConn,
				fmt.Sprintf("select id, name, display_name from %s order by id", testTable), withGeneratedColumn)
			if len(rows) != 3 {
				return false
			}

			want := []*testTableColumn{
				{id: 10, name: "alpha", username: "item_alpha"},
				{id: 20, name: "beta", username: "item_beta"},
				{id: 30, name: "gamma", username: "item_gamma"},
			}
			require.Equal(t, want, rows)
			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync of identity+generated table")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}

// Test_SnapshotToPostgres_LargeIntegerPrecision verifies that snapshot/restore
// preserves int64 precision for both:
//   - plain bigint columns whose value exceeds 2^53 (#824), and
//   - large integer values embedded inside json/jsonb columns (#686).
//
// Without the custom internal/json.UnmarshalUseInt64 decoder, JSON integers
// are silently rounded to float64 — the destination row diverges from the
// source by one or more units with no error or warning.
func Test_SnapshotToPostgres_LargeIntegerPrecision(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		testTable := fmt.Sprintf("largeint_%s", suffix)

		// 9007199254740993 = 2^53 + 1, the smallest int64 that float64
		// cannot represent exactly. 9223372036854775807 is MaxInt64.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id      bigint PRIMARY KEY,
				amount  bigint NOT NULL,
				payload jsonb  NOT NULL
			)`, testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, amount, payload) VALUES
				(9007199254740993,    9007199254740993,    '{"n":9007199254740993}'),
				(9223372036854775807, 9223372036854775807, '{"n":9223372036854775807,"nested":{"k":1234567890123456789}}')`,
			testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)
		sourceConn, err := pglib.NewConn(ctx, snapshotPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		type row struct {
			id      int64
			amount  int64
			payload string
		}
		query := fmt.Sprintf(
			"SELECT id, amount, payload::text FROM %s ORDER BY id", testTable)
		fetch := func(conn pglib.Querier) ([]row, error) {
			rows, err := conn.Query(ctx, query)
			if err != nil {
				return nil, err
			}
			defer rows.Close()
			out := []row{}
			for rows.Next() {
				var r row
				if err := rows.Scan(&r.id, &r.amount, &r.payload); err != nil {
					return nil, err
				}
				out = append(out, r)
			}
			return out, rows.Err()
		}

		want, err := fetch(sourceConn)
		require.NoError(t, err)
		require.Len(t, want, 2)
		// Belt-and-braces: confirm the source actually stores the
		// large ints we asked for. If this fails the test setup is
		// wrong, not the production code.
		require.Equal(t, int64(9007199254740993), want[0].id)
		require.Equal(t, int64(9223372036854775807), want[1].id)
		require.Contains(t, want[1].payload, `"k": 1234567890123456789`)

		validation := func() bool {
			got, err := fetch(targetConn)
			if err != nil || len(got) != len(want) {
				return false
			}
			require.Equal(t, want, got)
			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for large-int snapshot sync")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}
