// SPDX-License-Identifier: Apache-2.0

package integration

import (
	"context"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	pglib "github.com/xataio/pgstream/internal/postgres"
	"github.com/xataio/pgstream/internal/testcontainers"
	"github.com/xataio/pgstream/pkg/stream"
)

func Test_SnapshotToPostgres(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	// postgres container where pgstream hasn't been initialised to be used for
	// snapshot validation
	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(testTable string, opts ...option) {
		// create table and populate it before initialising and running pgstream to
		// ensure the snapshot captures pre-existing schema and data properly
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(`CREATE TABLE %s(id serial PRIMARY KEY, name TEXT, username TEXT GENERATED ALWAYS AS ('user_' || name ) STORED)`, testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf("insert into %s(name) values('a'),('b')", testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf("create role test_role_%s", testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf("grant select on %s to test_role_%s", testTable, testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		validation := func() bool {
			schemaColumns := getInformationSchemaColumns(t, ctx, targetConn, testTable)
			if len(schemaColumns) != 3 {
				return false
			}

			wantSchemaCols := []*informationSchemaColumn{
				{name: "id", dataType: "integer", isNullable: "NO"},
				{name: "name", dataType: "text", isNullable: "YES"},
				{name: "username", dataType: "text", isNullable: "YES"},
			}
			require.ElementsMatch(t, wantSchemaCols, schemaColumns)

			columns := getTestTableColumns(t, ctx, targetConn, fmt.Sprintf("select id,name,username from %s", testTable), withGeneratedColumn)
			if len(columns) != 2 {
				return false
			}

			wantCols := []*testTableColumn{
				{id: 1, name: "a", username: "user_a"},
				{id: 2, name: "b", username: "user_b"},
			}
			require.ElementsMatch(t, wantCols, columns)

			roles := getRoles(t, ctx, targetConn)
			require.NotEmpty(t, roles)
			require.Contains(t, roles, "test_role_"+testTable)

			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("snapshot2pg_bulk_integration_test", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("snapshot2pg_batch_integration_test")
	})
}

// Test_SnapshotToPostgres_IdentityOnlyTable verifies that tables where the only
// column is an identity column (e.g. id-only lookup tables) are correctly
// snapshotted, and that their values are preserved so that foreign key
// references from child tables remain valid.
func Test_SnapshotToPostgres_IdentityOnlyTable(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		parentTable := fmt.Sprintf("parent_identity_%s", suffix)
		childTable := fmt.Sprintf("child_identity_%s", suffix)

		// Create a parent table where id is the only column (identity).
		// This is the minimal repro: filterRowColumns used to filter out
		// all columns, producing zero insert queries.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`, parentTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id) VALUES (100),(200),(300)`, parentTable))

		// Create a child table that references the parent via FK.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				parent_id INTEGER NOT NULL REFERENCES %s(id),
				name TEXT
			)`, childTable, parentTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, parent_id, name) VALUES (1, 100, 'a'),(2, 200, 'b'),(3, 300, 'c')`, childTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		validation := func() bool {
			// Verify parent table: all 3 rows with exact id values preserved
			parentRows := getIDRows(t, ctx, targetConn, fmt.Sprintf("SELECT id FROM %s ORDER BY id", parentTable))
			if len(parentRows) != 3 {
				return false
			}
			require.Equal(t, []int{100, 200, 300}, parentRows)

			// Verify child table: all 3 rows with correct FK references
			childRows := getIDNameRows(t, ctx, targetConn, fmt.Sprintf("SELECT parent_id, name FROM %s ORDER BY id", childTable))
			if len(childRows) != 3 {
				return false
			}
			wantChildren := []idNameRow{
				{id: 100, name: "a"},
				{id: 200, name: "b"},
				{id: 300, name: "c"},
			}
			require.Equal(t, wantChildren, childRows)

			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync of identity-only tables")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}

// Test_SnapshotToPostgres_IdentityAndGeneratedColumns verifies that identity
// columns have their values preserved while generated (stored) columns are
// correctly excluded from inserts and recomputed by the target database.
func Test_SnapshotToPostgres_IdentityAndGeneratedColumns(t *testing.T) {
	if os.Getenv("PGSTREAM_INTEGRATION_TESTS") == "" {
		t.Skip("skipping integration test...")
	}

	var snapshotPGURL string
	pgcleanup, err := testcontainers.SetupPostgresContainer(context.Background(), &snapshotPGURL, testcontainers.Postgres14, "config/postgresql.conf")
	require.NoError(t, err)
	defer pgcleanup()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	run := func(suffix string, opts ...option) {
		testTable := fmt.Sprintf("identity_generated_%s", suffix)

		// Table with both an identity column (id) and a generated stored column (display_name).
		// The identity value must be preserved; the generated column must be excluded
		// from inserts and recomputed on the target.
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`CREATE TABLE %s(
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name TEXT NOT NULL,
				display_name TEXT GENERATED ALWAYS AS ('item_' || name) STORED
			)`, testTable))
		execQueryWithURL(t, ctx, snapshotPGURL, fmt.Sprintf(
			`INSERT INTO %s(id, name) VALUES (10, 'alpha'),(20, 'beta'),(30, 'gamma')`, testTable))

		cfg := &stream.Config{
			Listener:  testPostgresListenerCfgWithSnapshot(snapshotPGURL, targetPGURL, []string{"*.*"}),
			Processor: testPostgresProcessorCfg(opts...),
		}
		initStream(t, ctx, snapshotPGURL)
		runSnapshot(t, ctx, cfg)

		targetConn, err := pglib.NewConn(ctx, targetPGURL)
		require.NoError(t, err)

		timer := time.NewTimer(20 * time.Second)
		defer timer.Stop()
		ticker := time.NewTicker(time.Second)
		defer ticker.Stop()

		validation := func() bool {
			rows := getTestTableColumns(t, ctx, targetConn,
				fmt.Sprintf("select id, name, display_name from %s order by id", testTable), withGeneratedColumn)
			if len(rows) != 3 {
				return false
			}

			want := []*testTableColumn{
				{id: 10, name: "alpha", username: "item_alpha"},
				{id: 20, name: "beta", username: "item_beta"},
				{id: 30, name: "gamma", username: "item_gamma"},
			}
			require.Equal(t, want, rows)
			return true
		}

		for {
			select {
			case <-timer.C:
				cancel()
				t.Error("timeout waiting for postgres snapshot sync of identity+generated table")
				return
			case <-ticker.C:
				if validation() {
					return
				}
			}
		}
	}

	t.Run("bulk ingest", func(t *testing.T) {
		run("bulk", withBulkIngestionEnabled())
	})
	t.Run("batch writer", func(t *testing.T) {
		run("batch")
	})
}
